'use client'

import type { Metadata } from "next";
import Sider from 'antd/es/layout/Sider';
import { useState } from 'react';
import SidebarTree from './SidebarTreeOld';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Sidebar() {
  const [collapsed, setCollapsed] = useState(false);

  return (
    <Sider collapsible collapsed={collapsed} onCollapse={(value) => setCollapsed(value)}>
      <div className="demo-logo-vertical" />
      <SidebarTree />
    </Sider>
  );
}
